"""Top MCP/ClawHub skills as mesh descriptors."""

MCP_SKILLS = [
    # Top installed (Anthropic official)
    {
        "type": "mcp/tool/web-fetch",
        "endpoint": "npx:-y:@anthropic/mcp-server-fetch",
        "params": {
            "name": "Web Fetch",
            "protocol": "mcp",
            "transport": "stdio",
            "installs": "180000+",
            "description": "Fetch web pages for research and fact-checking",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/brave-search",
        "endpoint": "npx:-y:@anthropic/mcp-server-brave-search",
        "params": {
            "name": "Brave Search",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Web search via Brave Search API",
            "auth": {"method": "api_key", "key_name": "BRAVE_API_KEY", "signup_url": "https://brave.com/search/api/"},
            "pricing": {"model": "freemium", "free_tier": "2,000 queries/month", "paid_url": "https://brave.com/search/api/"},
        },
    },
    {
        "type": "mcp/tool/filesystem",
        "endpoint": "npx:-y:@anthropic/mcp-server-filesystem",
        "params": {
            "name": "Filesystem",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Read, write, and manage files",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/github",
        "endpoint": "npx:-y:@anthropic/mcp-server-github",
        "params": {
            "name": "GitHub",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "GitHub API integration — repos, issues, PRs",
            "auth": {"method": "api_key", "key_name": "GITHUB_TOKEN", "signup_url": "https://github.com/settings/tokens"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/postgres",
        "endpoint": "npx:-y:@anthropic/mcp-server-postgres",
        "params": {
            "name": "PostgreSQL",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Query PostgreSQL databases",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/sqlite",
        "endpoint": "npx:-y:@anthropic/mcp-server-sqlite",
        "params": {
            "name": "SQLite",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Read and query SQLite databases",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/memory",
        "endpoint": "npx:-y:@anthropic/mcp-server-memory",
        "params": {
            "name": "Memory",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Persistent memory via knowledge graph",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/puppeteer",
        "endpoint": "npx:-y:@anthropic/mcp-server-puppeteer",
        "params": {
            "name": "Puppeteer",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Browser automation via Puppeteer",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/slack",
        "endpoint": "npx:-y:@anthropic/mcp-server-slack",
        "params": {
            "name": "Slack",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Slack workspace integration",
            "auth": {"method": "api_key", "key_name": "SLACK_TOKEN", "signup_url": "https://api.slack.com/apps"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/google-maps",
        "endpoint": "npx:-y:@anthropic/mcp-server-google-maps",
        "params": {
            "name": "Google Maps",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Geocoding, directions, places",
            "auth": {"method": "api_key", "key_name": "GOOGLE_MAPS_KEY", "signup_url": "https://console.cloud.google.com/apis/credentials"},
            "pricing": {"model": "freemium", "free_tier": "$200/month free credit", "paid_url": "https://developers.google.com/maps/billing"},
        },
    },
    # Popular community skills
    {
        "type": "mcp/tool/tavily-search",
        "endpoint": "npx:-y:tavily-mcp-server",
        "params": {
            "name": "Tavily Search",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "AI-optimized web search",
            "auth": {"method": "api_key", "key_name": "TAVILY_API_KEY", "signup_url": "https://tavily.com"},
            "pricing": {"model": "freemium", "free_tier": "1,000 credits/month", "paid_url": "https://tavily.com/pricing"},
        },
    },
    {
        "type": "mcp/tool/playwright",
        "endpoint": "npx:-y:@anthropic/mcp-server-playwright",
        "params": {
            "name": "Playwright",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Browser automation via Playwright",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/sequential-thinking",
        "endpoint": "npx:-y:@anthropic/mcp-server-sequential-thinking",
        "params": {
            "name": "Sequential Thinking",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Step-by-step reasoning tool",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/context7",
        "endpoint": "npx:-y:@context7/mcp-server",
        "params": {
            "name": "Context7",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Up-to-date library documentation",
            "auth": {"method": "none"},
            "pricing": {"model": "free"},
        },
    },
    {
        "type": "mcp/tool/firecrawl",
        "endpoint": "npx:-y:firecrawl-mcp",
        "params": {
            "name": "Firecrawl",
            "protocol": "mcp",
            "transport": "stdio",
            "description": "Web scraping and crawling",
            "auth": {"method": "api_key", "key_name": "FIRECRAWL_API_KEY", "signup_url": "https://firecrawl.dev"},
            "pricing": {"model": "freemium", "free_tier": "500 credits/month", "paid_url": "https://firecrawl.dev/pricing"},
        },
    },
]
