#!/usr/bin/env bash
# ============================================================================
# Mesh Hub — Hetzner VPS Setup Script
# ============================================================================
# Run this on a fresh Hetzner CX22 (or similar) running Debian 12 / Ubuntu 24.
#
# Usage:
#   scp deploy/setup-hetzner.sh root@YOUR_VPS_IP:~
#   ssh root@YOUR_VPS_IP bash setup-hetzner.sh
#
# What it does:
#   1. Creates a 'mesh' system user
#   2. Installs the mesh-hub binary (you must build and upload it first)
#   3. Generates a hub identity keypair
#   4. Writes a default config
#   5. Opens UDP 4433 in the firewall
#   6. Installs and starts the systemd service

set -euo pipefail

echo "=== Mesh Hub Setup ==="

# ── System user ──────────────────────────────────────────────────────────────

if ! id mesh &>/dev/null; then
    useradd --system --create-home --shell /usr/sbin/nologin mesh
    echo "Created system user: mesh"
fi

# ── Directories ──────────────────────────────────────────────────────────────

mkdir -p /etc/mesh-hub
mkdir -p /var/lib/mesh-hub/data
chown -R mesh:mesh /var/lib/mesh-hub

# ── Binary ───────────────────────────────────────────────────────────────────

if [ ! -f /usr/local/bin/mesh-hub ]; then
    echo ""
    echo "ERROR: /usr/local/bin/mesh-hub not found."
    echo ""
    echo "Build and upload the binary first:"
    echo "  cargo build --release --bin mesh-hub"
    echo "  scp target/release/mesh-hub root@YOUR_VPS_IP:/usr/local/bin/"
    echo ""
    exit 1
fi

chmod +x /usr/local/bin/mesh-hub

# ── Identity ─────────────────────────────────────────────────────────────────

KEYPAIR_PATH="/var/lib/mesh-hub/data/hub-identity.key"
if [ ! -f "$KEYPAIR_PATH" ]; then
    sudo -u mesh mesh-hub --config /dev/null --generate-keypair 2>/dev/null || true
    # Fallback: generate with the mesh-hub binary directly
    if [ ! -f "$KEYPAIR_PATH" ]; then
        sudo -u mesh /usr/local/bin/mesh-hub --generate-keypair --config <(cat <<TMPCONF
[identity]
keypair_path = "$KEYPAIR_PATH"
[network]
listen_addr = "0.0.0.0:4433"
admin_addr = "127.0.0.1:8080"
TMPCONF
) || echo "Generate keypair manually: mesh-hub --generate-keypair"
    fi
fi

# ── Operator token ───────────────────────────────────────────────────────────

OPERATOR_TOKEN=$(openssl rand -hex 32)

# ── Config ───────────────────────────────────────────────────────────────────

if [ ! -f /etc/mesh-hub/mesh-hub.toml ]; then
    cat > /etc/mesh-hub/mesh-hub.toml <<TOML
# Mesh Hub Configuration — generated by setup-hetzner.sh
# Full reference: https://github.com/marshallbrett/mesh-protocol/blob/master/docs/operator-guide.md

[identity]
keypair_path = "/var/lib/mesh-hub/data/hub-identity.key"

[network]
listen_addr = "0.0.0.0:4433"
admin_addr = "127.0.0.1:8080"

[storage]
data_dir = "/var/lib/mesh-hub/data"
hot_cache_entries = 50000

[tenants]
enabled = true
db_path = "/var/lib/mesh-hub/data/tenants.sqlite"

[policy]
store_mode = "tenant-only"

[security]
max_connections_per_ip = 50
max_queries_per_identity_per_sec = 20
admin_bearer_token = "$OPERATOR_TOKEN"

[observability]
metrics_enabled = true

operator_token = "$OPERATOR_TOKEN"
TOML
    chown mesh:mesh /etc/mesh-hub/mesh-hub.toml
    chmod 640 /etc/mesh-hub/mesh-hub.toml
    echo "Config written to /etc/mesh-hub/mesh-hub.toml"
fi

# ── Firewall ─────────────────────────────────────────────────────────────────

if command -v ufw &>/dev/null; then
    ufw allow 4433/udp comment "mesh-hub QUIC"
    echo "Opened UDP 4433 (ufw)"
elif command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-port=4433/udp
    firewall-cmd --reload
    echo "Opened UDP 4433 (firewalld)"
else
    echo "NOTE: Open UDP port 4433 in your firewall manually."
fi

# ── Systemd ──────────────────────────────────────────────────────────────────

cp "$(dirname "$0")/mesh-hub.service" /etc/systemd/system/mesh-hub.service 2>/dev/null \
    || echo "Copy deploy/mesh-hub.service to /etc/systemd/system/ manually."

systemctl daemon-reload
systemctl enable mesh-hub
systemctl start mesh-hub

echo ""
echo "=== Setup Complete ==="
echo ""
echo "  Hub status:      systemctl status mesh-hub"
echo "  Hub logs:        journalctl -u mesh-hub -f"
echo "  Admin API:       curl -H 'Authorization: Bearer $OPERATOR_TOKEN' http://127.0.0.1:8080/health"
echo "  Operator token:  $OPERATOR_TOKEN"
echo ""
echo "  SAVE YOUR OPERATOR TOKEN — it is not stored anywhere else."
echo ""
