#!/usr/bin/env bash
# ============================================================================
# Mesh Hub — Hetzner VPS Setup Script (Multi-Region)
# ============================================================================
# Run this on a fresh Hetzner CX22 (or similar) running Debian 12 / Ubuntu 24.
#
# Usage:
#   setup-hetzner.sh <region> [seed_addr]
#
# Regions:
#   us-east       Ashburn, VA
#   us-west       Hillsboro, OR
#   eu-central    Falkenstein/Nuremberg, DE
#   ap-southeast  Singapore
#
# First hub (no seed):
#   setup-hetzner.sh us-east
#
# Subsequent hubs (peer with existing):
#   setup-hetzner.sh us-west 1.2.3.4:4433
#   setup-hetzner.sh eu-central 1.2.3.4:4433
#   setup-hetzner.sh ap-southeast 1.2.3.4:4433
#
# What it does:
#   1. Creates a 'mesh' system user
#   2. Installs the mesh-hub binary (build and upload first)
#   3. Generates a hub identity keypair
#   4. Writes a region-aware config with peering enabled
#   5. Opens UDP 4433 in the firewall
#   6. Installs and starts the systemd service

set -euo pipefail

# ── Arguments ────────────────────────────────────────────────────────────────

REGION="${1:-}"
SEED_ADDR="${2:-}"

if [ -z "$REGION" ]; then
    echo "Usage: setup-hetzner.sh <region> [seed_addr]"
    echo ""
    echo "Regions: us-east, us-west, eu-central, ap-southeast"
    echo ""
    echo "Examples:"
    echo "  setup-hetzner.sh us-east                    # first hub, no seed"
    echo "  setup-hetzner.sh us-west 1.2.3.4:4433       # peer with us-east"
    exit 1
fi

case "$REGION" in
    us-east|us-west|eu-central|ap-southeast) ;;
    *)
        echo "ERROR: Unknown region '$REGION'"
        echo "Valid regions: us-east, us-west, eu-central, ap-southeast"
        exit 1
        ;;
esac

echo "=== Mesh Hub Setup — $REGION ==="

# ── Detect public IP ─────────────────────────────────────────────────────────

PUBLIC_IP=$(curl -s -4 ifconfig.me || curl -s -4 icanhazip.com || echo "UNKNOWN")
echo "  Public IP: $PUBLIC_IP"

# ── System user ──────────────────────────────────────────────────────────────

if ! id mesh &>/dev/null; then
    useradd --system --create-home --shell /usr/sbin/nologin mesh
    echo "  Created system user: mesh"
fi

# ── Directories ──────────────────────────────────────────────────────────────

mkdir -p /etc/mesh-hub
mkdir -p /var/lib/mesh-hub/data
chown -R mesh:mesh /var/lib/mesh-hub

# ── Binary ───────────────────────────────────────────────────────────────────

if [ ! -f /usr/local/bin/mesh-hub ]; then
    echo ""
    echo "ERROR: /usr/local/bin/mesh-hub not found."
    echo ""
    echo "Build and upload the binary first:"
    echo "  cargo build --release --bin mesh-hub"
    echo "  scp target/release/mesh-hub root@$PUBLIC_IP:/usr/local/bin/"
    echo ""
    exit 1
fi

chmod +x /usr/local/bin/mesh-hub

# ── Identity ─────────────────────────────────────────────────────────────────

KEYPAIR_PATH="/var/lib/mesh-hub/data/hub-identity.key"
if [ ! -f "$KEYPAIR_PATH" ]; then
    # Generate a 32-byte Ed25519 secret key
    openssl rand 32 > "$KEYPAIR_PATH"
    chown mesh:mesh "$KEYPAIR_PATH"
    chmod 600 "$KEYPAIR_PATH"
    echo "  Generated hub identity keypair"
fi

# ── Operator token ───────────────────────────────────────────────────────────

OPERATOR_TOKEN=$(openssl rand -hex 32)

# ── Config ───────────────────────────────────────────────────────────────────

if [ ! -f /etc/mesh-hub/mesh-hub.toml ]; then

    # Build outbound_allowlist for peer IPs (allow SSRF check to pass for peers)
    ALLOWLIST=""
    if [ -n "$SEED_ADDR" ]; then
        ALLOWLIST="outbound_allowlist = [\"$SEED_ADDR\"]"
    fi

    cat > /etc/mesh-hub/mesh-hub.toml <<TOML
# Mesh Hub Configuration — $REGION
# Generated by setup-hetzner.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Full reference: https://github.com/marshallbrett/mesh-protocol/blob/master/docs/operator-guide.md

[identity]
keypair_path = "/var/lib/mesh-hub/data/hub-identity.key"

[network]
listen_addr = "0.0.0.0:4433"
admin_addr = "127.0.0.1:8080"

[storage]
data_dir = "/var/lib/mesh-hub/data"
hot_cache_entries = 50000

[tenants]
enabled = true
db_path = "/var/lib/mesh-hub/data/tenants.sqlite"

[policy]
store_mode = "tenant-only"

[security]
max_connections_per_ip = 50
max_queries_per_identity_per_sec = 20
admin_bearer_token = "$OPERATOR_TOKEN"
$ALLOWLIST

[mu_costs]
store_new = 10
store_update = 5
find_value = 1
find_node = 1

[peering]
enabled = true
gossip_interval_secs = 60
health_check_interval_secs = 10
max_peers = 50
regions = ["$REGION"]
max_descriptors = 1000000

[observability]
metrics_enabled = true

operator_token = "$OPERATOR_TOKEN"
TOML

    chown mesh:mesh /etc/mesh-hub/mesh-hub.toml
    chmod 640 /etc/mesh-hub/mesh-hub.toml
    echo "  Config written to /etc/mesh-hub/mesh-hub.toml"
else
    echo "  Config already exists, skipping"
fi

# ── Firewall ─────────────────────────────────────────────────────────────────

if command -v ufw &>/dev/null; then
    ufw allow 4433/udp comment "mesh-hub QUIC" 2>/dev/null || true
    echo "  Opened UDP 4433 (ufw)"
elif command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-port=4433/udp 2>/dev/null || true
    firewall-cmd --reload
    echo "  Opened UDP 4433 (firewalld)"
else
    echo "  NOTE: Open UDP port 4433 in your firewall manually."
fi

# ── Systemd ──────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/mesh-hub.service" ]; then
    cp "$SCRIPT_DIR/mesh-hub.service" /etc/systemd/system/mesh-hub.service
else
    echo "  WARNING: mesh-hub.service not found next to this script."
    echo "  Copy deploy/mesh-hub.service to /etc/systemd/system/ manually."
fi

systemctl daemon-reload
systemctl enable mesh-hub
systemctl start mesh-hub

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "=== Hub Online — $REGION ==="
echo ""
echo "  Public address:  $PUBLIC_IP:4433"
echo "  Region:          $REGION"
echo "  Peering:         enabled"
if [ -n "$SEED_ADDR" ]; then
echo "  Seed peer:       $SEED_ADDR"
fi
echo ""
echo "  Hub status:      systemctl status mesh-hub"
echo "  Hub logs:        journalctl -u mesh-hub -f"
echo "  Admin API:       curl -H 'Authorization: Bearer $OPERATOR_TOKEN' http://127.0.0.1:8080/health"
echo ""
echo "  Operator token:  $OPERATOR_TOKEN"
echo "  SAVE THIS TOKEN — it is not stored anywhere else."
echo ""
if [ -z "$SEED_ADDR" ]; then
echo "  This is the first hub. When setting up the next region, use:"
echo "    setup-hetzner.sh <region> $PUBLIC_IP:4433"
echo ""
fi
